#!/usr/bin/env bash
#

die() {
  echo "$1" >&2
  exit 1
}

WORK_BRANCH="work"

export GIT_WORK_TREE="$( cd ../ && pwd -L )"

git sync lock || die
branch_name="$(git symbolic-ref HEAD 2>/dev/null)" ||
branch_name="(unnamed branch)"     # detached HEAD
branch_name=${branch_name##refs/heads/}
if [ "$branch_name" != "$WORK_BRANCH" ]; then
  git sync unlock
  die "on branch \"$branch_name\"; must be on branch ${WORK_BRANCH}"
fi
git reset --hard || die
git sync unlock
